print('py init')
#     cmd      path    disp info cost acess
init('i', 'example.py', 1, 'info', 0, 1)
#init('masta', 'ms_xash.py', 1, 'xash servers', 0, 1)
#init('music', 'music.py', 1, 'music search', 0, 1)
init('r34', 'r34.py', 0, 'rule 34)', 0, 1)
init('cl', 'clean.py', 1, 'clean msg in this chat', 0, 1)
init('x', 'xash.py', 1, 'xash3d dev android version', 0, 1)
init('k', 'kick.py', 0, 'random', 0, 1)
init('a', 'add.py', 0, 'random', 0, 1)
init('лурк', 'lurk.py', 1, 'поиск по лурку', 0, 1)
init('chat', 'chat.py', 1, 'стата чата', 0, 1)
init('allchats', 'allchats.py', 1, 'стата чата', 0, 5)
init('вики', 'wiki_ru.py', 1, 'ru.wikipedia.org', 0, 1)
init('wiki', 'wiki_en.py', 1, 'en.wikipedia.org', 0, 1)
init('s', 'solar.py', 1, 'http://www2.irf.se/Observatory/?link=Magnetometers', 0, 1)
init('a', 'online.py', 1, 'chat online', 0, 1)
init('scr', 'scr.py', 1, 'скрин сайта', 0, 1)