print('py init')
#     cmd      path    disp info cost acess
init('i', 'example.py', 1, 'info', 0, 1)
init('masta', 'ms_xash.py', 1, 'xash servers', 0, 1)
init('music', 'music.py', 1, 'music search', 0, 1)
init('r34', 'r34.py', 0, 'rule 34)', 0, 1)
init('c', 'code.py', 1, 'code msg', 0, 1)
init('d', 'decode.py', 1, 'decode msg', 0, 1)
init('cl', 'clean.py', 1, 'clean msg in this chat', 0, 1)
init('x', 'xash.py', 0, 'xash3d dev android version', 0, 1)
init('k', 'kick.py', 0, 'random', 0, 1)
init('лурк', 'lurk.py', 0, 'поиск по лурку', 0, 1)
init('chat', 'chat.py', 0, 'стата чата', 0, 1)
init('allchats', 'allchats.py', 0, 'стата чата', 0, 5)
